### ISSUE TITLE
Incomplete: The Nigerian Constitution may have missing sections

### ISSUE THREAD

**Issue by mykeels** [mykeels/nigerian-constitution#1]
The Nigerian constitution was scraped from [this page](http://www.nigeria-law.org/ConstitutionOfTheFederalRepublicOfNigeria.htm), which has poor HTML formatting, so there are missing sections like 

- [Chapter VII](https://github.com/mykeels/nigerian-constitution/blob/master/constitution/chapter-vii.md) missing sections:
 - [x] Section 295
 - [x] Section 296

Please get them from [here](http://www.nigeria-law.org/ConstitutionOfTheFederalRepublicOfNigeria.htm#Supplemental) and place in [this file](https://github.com/mykeels/nigerian-constitution/blob/master/constitution/chapter-vii.md)

**Comment by Mrchux** [comment]
I have gone through your instructions, pretty straight forward.

**Comment by mykeels** [comment]
Nice! @Mrchux Do I take it you'll be working on this issue?

**Comment by mykeels** [comment]
Done!
